import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance';

export const modelSettingsAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'model-settings',
  parts: [
    { id: 'root' },
    { id: 'providerSelection' },
    { id: 'customOption' },
    { id: 'customOptionTitle' },
    { id: 'customOptionDescription' },
    { id: 'selectionDivider' },
    { id: 'providerSearch' },
    { id: 'providerList' },
    { id: 'providerRow' },
    { id: 'providerSelect' },
    { id: 'providerName' },
    { id: 'providerDescription' },
    { id: 'providerEmpty' },
    { id: 'providerMore' },
    { id: 'selectionActions' },
    { id: 'form' },
    { id: 'formBody' },
    { id: 'subscriptionArea' },
    { id: 'subscriptionPanel' },
    { id: 'subscriptionSummary' },
    { id: 'subscriptionCode' },
    { id: 'subscriptionActions' },
    { id: 'collection' },
    { id: 'empty' },
    { id: 'providerGroup' },
    { id: 'providerGroupHeader' },
    { id: 'providerGroupTitle' },
    { id: 'providerGroupActions' },
    { id: 'providerGroupList' },
    { id: 'modelItem' },
    { id: 'modelMeta' },
    { id: 'modelActions' },
    { id: 'modelDetails' },
    { id: 'logoutConfirm' },
    { id: 'quickSetup' },
    { id: 'quickSetupStep' },
    { id: 'quickSetupProvider' },
    { id: 'quickSetupProviderName' },
    { id: 'quickSetupProviderDesc' },
    { id: 'quickSetupModel' },
    { id: 'quickSetupModelName' },
    { id: 'quickSetupModelBadge' },
    { id: 'quickSetupModelDesc' },
    { id: 'quickSetupFooter' },
    { id: 'quickSetupResult' },
    { id: 'quickSetupHelp' },
    { id: 'quickSetupError' },
    { id: 'providersLayout' },
    { id: 'providersColumn' },
    { id: 'providersColumnTitle' },
    { id: 'providersCard' },
    { id: 'providersCardName' },
    { id: 'providersCardDesc' },
    { id: 'providersCardStatus' },
    { id: 'providersCardBadge' },
    { id: 'providersCardBody' },
    { id: 'providersCardActions' },
    { id: 'providersCardHelp' },
    { id: 'providersCardHint' },
    { id: 'providersCardAccount' },
    { id: 'providersCardError' },
    { id: 'providersCardSuccess' },
    { id: 'providersModelList' },
    { id: 'providersModelOption' },
    { id: 'providersModelName' },
    { id: 'providersModelDesc' },
  ],
  facets: [
    { id: 'view', attribute: 'data-openbitfun-view', values: ['selection', 'settings'] },
    { id: 'status', attribute: 'data-openbitfun-status', values: ['starting', 'pending', 'cancelling', 'failed'] },
  ],
  states: [
    { id: 'hover', selector: { kind: 'self', suffix: ':hover' } },
    { id: 'expanded', selector: { kind: 'self', suffix: '[data-openbitfun-state~="expanded"]' } },
    { id: 'disabled', selector: { kind: 'self', suffix: '[data-openbitfun-state~="disabled"]' } },
  ],
};
